---
title: "Homework 5"
author: Leo Liu
output: github_document
---

```{r}
library(tidyverse)
library(purrr)
```


# Question 1

```{r}
library(xml2)

homicide_df = read_csv("homicide-data.csv") %>% 
  mutate(
    city_state = str_c(city, state, sep = "_"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved"
    )
  ) %>% 
  select(city_state, resolved) %>% 
  filter(city_state != "Tulsa_AL")
```

```{r}
homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    hom_total = n(),
    hom_unsolved = sum(resolved == "unsolved")
  )

aggregate_df = 
  homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    hom_total = n(),
    hom_unsolved = sum(resolved == "unsolved")
  )
```

```{r}
results_df = 
  aggregate_df %>% 
  mutate(
    prop_tests = map2(.x = hom_unsolved, .y = hom_total, ~prop.test(x = .x, n = .y)),
    tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))
  ) %>% 
  select(-prop_tests) %>% 
  unnest(tidy_tests) %>% 
  select(city_state, estimate, conf.low, conf.high)
```

```{r}
results_df %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point()
```

```{r}
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```


# Question 2

```{r}
read_plus <- function(flnm) {
    read_csv(flnm) %>% 
        mutate(filename = flnm)
}

df2 = list.files("hw5_data", full.names = T) %>% 
  map_df(~read_plus(.)) %>% 
  janitor::clean_names() %>%
  separate(filename,
           into = c("file", "id"),
           sep = "/") %>%
  mutate(id = substr(id, 0, 6),
         arm = case_when(
    str_detect(id, "con") ~ "con",
    str_detect(id, "exp") ~ "exp")) %>% 
  select(arm, id, week_1:week_8) %>% 
  pivot_longer(week_1:week_8,
               names_to = "weeks",
               values_to = "observations")


plt = 
df2 %>% 
  ggplot(aes(x = weeks, y = observations, group = interaction(arm, id), color = arm)) +
  geom_point() +
  geom_line() +
  theme_bw()

plt

```


# Question 3

```{r}
sim_mean = function(samp_size = 30, mu, sigma = 5) {
  sim_data = 
  tibble(
    x = rnorm(n = samp_size, mean = mu, sd = sigma)
  )
  ttest = t.test(sim_data, mu = 0, conf.level = 0.95) %>% 
    broom::tidy()

sim_data %>% 
  summarize(
    mean = mean(x),
    sd = sd(x)
  ) %>% 
  mutate(p_value = pull(ttest, p.value),
         outputs = ifelse(p_value < 0.05,
                          1, 0))
}


output_list = vector("list", length = 6)
sim_result = tibble(
  mu = c(1,2,3,4,5,6)
) %>% 
  mutate(sim_list = map(.x = mu, ~rerun(5000, sim_mean(mu = .x))),
         estimates = map(sim_list, bind_rows),
         prob_rej = map(.x = estimates, ~(sum(.x$outputs)) / nrow(.x))) %>% 
  select(-sim_list) %>% 
  unnest(estimates)

sim_result_1 = sim_result %>% 
  select(mu, prob_rej) %>% 
  distinct()

plt1 = sim_result_1 %>% 
  unnest(prob_rej) %>% 
  ggplot(aes(x = mu,
             y = prob_rej)) +
         scale_x_continuous(breaks = c(1,2,3,4,5,6)) +
  xlab("True Group Means") +
  ylab("Rejected Proportion") +
  ggtitle("Proportion of Rejection for Each True Mean") +
  geom_point() +
  geom_line()

plt1


sim_result_2 = sim_result %>% 
  group_by(mu) %>% 
  mutate(
    avg_samp_mean = mean(mean)
  ) %>% 
  select(mu, avg_samp_mean) %>% 
  distinct()

plt2 = 
sim_result_2 %>% 
ggplot(aes(x = mu,
           y = avg_samp_mean)) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6)) +
  scale_y_continuous(breaks = c(1,2,3,4,5,6)) +
  xlab("True Group Means") +
  ylab("Mean of Sample Means") +
  ggtitle("Mean of Sample Means vs. True Mean") +
  geom_point() + 
  geom_line() +
  theme_bw()

plt2


sim_result_3 = sim_result %>% 
  filter(outputs == 1) %>% 
  group_by(mu) %>% 
  mutate(avg_samp_mean = mean(mean)) %>% 
  select(mu, avg_samp_mean) %>% 
  distinct()

plt3 = sim_result_3 %>% 
  ggplot(aes(x = mu,
           y = avg_samp_mean)) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6)) +
  scale_y_continuous(breaks = c(1,2,3,4,5,6)) +
  xlab("True Group Means") +
  ylab("Mean of Sample Means (Rejected Samples Only)") +
  ggtitle("Mean of Sample Means (Null Rejected Only) vs. True Mean") +
  geom_point() +
  geom_line() +
  theme_bw()

plt3

```

Note that the difference between the "average estimate of mu vs. true mu" and the "mu in rejected samples vs. true mu" plots is largest at mu = 1. Eventually, the difference goes to 0. In the end, the means from the rejected simulation converge to the true mean. 

